# Включаем рекомендованные Flutter-ли́нты
include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    use_super_parameters: ignore
    use_build_context_synchronously: ignore

linter:
  rules:
    use_super_parameters: false
    use_build_context_synchronously: false
